<?php

return [
    'reporting_timezone' => 'Europe/London',

    'calling_hours' => [
        'start' => 9,
        'end' => 17,
    ],

    /*
    | Timezone lookup data used by lead batch clocks. The market list below is
    | intentionally curated for the discovery overview; these broader maps let
    | arbitrary batch locations resolve without adding every city to that UI.
    | A region match takes precedence over a city match so names such as
    | Portland, London, Birmingham, Manchester and Melbourne remain accurate.
    */
    'city_timezones' => [
        'adelaide' => 'Australia/Adelaide',
        'atlanta' => 'America/New_York',
        'auckland' => 'Pacific/Auckland',
        'austin' => 'America/Chicago',
        'birmingham' => 'Europe/London',
        'boston' => 'America/New_York',
        'brisbane' => 'Australia/Brisbane',
        'calgary' => 'America/Edmonton',
        'canberra' => 'Australia/Sydney',
        'charlotte' => 'America/New_York',
        'chicago' => 'America/Chicago',
        'christchurch' => 'Pacific/Auckland',
        'dallas' => 'America/Chicago',
        'darwin' => 'Australia/Darwin',
        'denver' => 'America/Denver',
        'dublin' => 'Europe/Dublin',
        'edmonton' => 'America/Edmonton',
        'gold coast' => 'Australia/Brisbane',
        'halifax' => 'America/Halifax',
        'hamilton' => 'America/Toronto',
        'hobart' => 'Australia/Hobart',
        'houston' => 'America/Chicago',
        'las vegas' => 'America/Los_Angeles',
        'london' => 'Europe/London',
        'los angeles' => 'America/Los_Angeles',
        'manchester' => 'Europe/London',
        'melbourne' => 'Australia/Melbourne',
        'miami' => 'America/New_York',
        'minneapolis' => 'America/Chicago',
        'mississauga' => 'America/Toronto',
        'montreal' => 'America/Toronto',
        'nashville' => 'America/Chicago',
        'new orleans' => 'America/Chicago',
        'new york' => 'America/New_York',
        'orlando' => 'America/New_York',
        'ottawa' => 'America/Toronto',
        'perth' => 'Australia/Perth',
        'philadelphia' => 'America/New_York',
        'phoenix' => 'America/Phoenix',
        'quebec city' => 'America/Toronto',
        'raleigh' => 'America/New_York',
        'regina' => 'America/Regina',
        'salt lake city' => 'America/Denver',
        'san diego' => 'America/Los_Angeles',
        'san francisco' => 'America/Los_Angeles',
        'saskatoon' => 'America/Regina',
        'seattle' => 'America/Los_Angeles',
        'sydney' => 'Australia/Sydney',
        'toronto' => 'America/Toronto',
        'vancouver' => 'America/Vancouver',
        'victoria' => 'America/Vancouver',
        'washington' => 'America/New_York',
        'wellington' => 'Pacific/Auckland',
        'winnipeg' => 'America/Winnipeg',
    ],

    'region_timezones' => [
        // United States — dominant timezone for each state; known cities above
        // and explicit region values win before a country-level fallback.
        'al' => 'America/Chicago', 'alabama' => 'America/Chicago',
        'ak' => 'America/Anchorage', 'alaska' => 'America/Anchorage',
        'az' => 'America/Phoenix', 'arizona' => 'America/Phoenix',
        'ar' => 'America/Chicago', 'arkansas' => 'America/Chicago',
        'ca' => 'America/Los_Angeles', 'california' => 'America/Los_Angeles',
        'co' => 'America/Denver', 'colorado' => 'America/Denver',
        'ct' => 'America/New_York', 'connecticut' => 'America/New_York',
        'de' => 'America/New_York', 'delaware' => 'America/New_York',
        'dc' => 'America/New_York', 'district of columbia' => 'America/New_York',
        'fl' => 'America/New_York', 'florida' => 'America/New_York',
        'ga' => 'America/New_York', 'georgia' => 'America/New_York',
        'hi' => 'Pacific/Honolulu', 'hawaii' => 'Pacific/Honolulu',
        'id' => 'America/Boise', 'idaho' => 'America/Boise',
        'il' => 'America/Chicago', 'illinois' => 'America/Chicago',
        'in' => 'America/Indiana/Indianapolis', 'indiana' => 'America/Indiana/Indianapolis',
        'ia' => 'America/Chicago', 'iowa' => 'America/Chicago',
        'ks' => 'America/Chicago', 'kansas' => 'America/Chicago',
        'ky' => 'America/New_York', 'kentucky' => 'America/New_York',
        'la' => 'America/Chicago', 'louisiana' => 'America/Chicago',
        'me' => 'America/New_York', 'maine' => 'America/New_York',
        'md' => 'America/New_York', 'maryland' => 'America/New_York',
        'ma' => 'America/New_York', 'massachusetts' => 'America/New_York',
        'mi' => 'America/Detroit', 'michigan' => 'America/Detroit',
        'mn' => 'America/Chicago', 'minnesota' => 'America/Chicago',
        'ms' => 'America/Chicago', 'mississippi' => 'America/Chicago',
        'mo' => 'America/Chicago', 'missouri' => 'America/Chicago',
        'mt' => 'America/Denver', 'montana' => 'America/Denver',
        'ne' => 'America/Chicago', 'nebraska' => 'America/Chicago',
        'nv' => 'America/Los_Angeles', 'nevada' => 'America/Los_Angeles',
        'nh' => 'America/New_York', 'new hampshire' => 'America/New_York',
        'nj' => 'America/New_York', 'new jersey' => 'America/New_York',
        'nm' => 'America/Denver', 'new mexico' => 'America/Denver',
        'ny' => 'America/New_York', 'new york' => 'America/New_York',
        'nc' => 'America/New_York', 'north carolina' => 'America/New_York',
        'nd' => 'America/Chicago', 'north dakota' => 'America/Chicago',
        'oh' => 'America/New_York', 'ohio' => 'America/New_York',
        'ok' => 'America/Chicago', 'oklahoma' => 'America/Chicago',
        'or' => 'America/Los_Angeles', 'oregon' => 'America/Los_Angeles',
        'pa' => 'America/New_York', 'pennsylvania' => 'America/New_York',
        'ri' => 'America/New_York', 'rhode island' => 'America/New_York',
        'sc' => 'America/New_York', 'south carolina' => 'America/New_York',
        'sd' => 'America/Chicago', 'south dakota' => 'America/Chicago',
        'tn' => 'America/Chicago', 'tennessee' => 'America/Chicago',
        'tx' => 'America/Chicago', 'texas' => 'America/Chicago',
        'ut' => 'America/Denver', 'utah' => 'America/Denver',
        'vt' => 'America/New_York', 'vermont' => 'America/New_York',
        'va' => 'America/New_York', 'virginia' => 'America/New_York',
        'wa' => 'America/Los_Angeles', 'washington' => 'America/Los_Angeles',
        'wv' => 'America/New_York', 'west virginia' => 'America/New_York',
        'wi' => 'America/Chicago', 'wisconsin' => 'America/Chicago',
        'wy' => 'America/Denver', 'wyoming' => 'America/Denver',

        // Canada.
        'ab' => 'America/Edmonton', 'alberta' => 'America/Edmonton',
        'bc' => 'America/Vancouver', 'british columbia' => 'America/Vancouver',
        'mb' => 'America/Winnipeg', 'manitoba' => 'America/Winnipeg',
        'nb' => 'America/Moncton', 'new brunswick' => 'America/Moncton',
        'nl' => 'America/St_Johns', 'newfoundland and labrador' => 'America/St_Johns',
        'ns' => 'America/Halifax', 'nova scotia' => 'America/Halifax',
        'nt' => 'America/Yellowknife', 'northwest territories' => 'America/Yellowknife',
        'nu' => 'America/Iqaluit', 'nunavut' => 'America/Iqaluit',
        'on' => 'America/Toronto', 'ontario' => 'America/Toronto',
        'pe' => 'America/Halifax', 'prince edward island' => 'America/Halifax',
        'qc' => 'America/Toronto', 'quebec' => 'America/Toronto',
        'sk' => 'America/Regina', 'saskatchewan' => 'America/Regina',
        'yt' => 'America/Whitehorse', 'yukon' => 'America/Whitehorse',

        // Australia.
        'nsw' => 'Australia/Sydney', 'new south wales' => 'Australia/Sydney',
        'vic' => 'Australia/Melbourne', 'victoria' => 'Australia/Melbourne',
        'qld' => 'Australia/Brisbane', 'queensland' => 'Australia/Brisbane',
        'wa australia' => 'Australia/Perth', 'western australia' => 'Australia/Perth',
        'sa' => 'Australia/Adelaide', 'south australia' => 'Australia/Adelaide',
        'tas' => 'Australia/Hobart', 'tasmania' => 'Australia/Hobart',
        'nt australia' => 'Australia/Darwin', 'northern territory' => 'Australia/Darwin',
        'act' => 'Australia/Sydney', 'australian capital territory' => 'Australia/Sydney',
    ],

    'country_timezones' => [
        'united kingdom' => 'Europe/London',
        'uk' => 'Europe/London',
        'ireland' => 'Europe/Dublin',
        'new zealand' => 'Pacific/Auckland',
        'jamaica' => 'America/Jamaica',
        'nigeria' => 'Africa/Lagos',
        'ghana' => 'Africa/Accra',
        'singapore' => 'Asia/Singapore',
        'philippines' => 'Asia/Manila',
    ],

    'markets' => [
        ['name' => 'London', 'country' => 'United Kingdom', 'location' => 'London, United Kingdom', 'timezone' => 'Europe/London', 'aliases' => ['Essex', 'Ware']],
        ['name' => 'Dublin', 'country' => 'Ireland', 'location' => 'Dublin, Ireland', 'timezone' => 'Europe/Dublin'],
        ['name' => 'Lagos', 'country' => 'Nigeria', 'location' => 'Lagos, Nigeria', 'timezone' => 'Africa/Lagos'],
        ['name' => 'Accra', 'country' => 'Ghana', 'location' => 'Accra, Ghana', 'timezone' => 'Africa/Accra'],
        ['name' => 'Toronto', 'country' => 'Canada', 'location' => 'Toronto, Canada', 'timezone' => 'America/Toronto'],
        ['name' => 'New York', 'country' => 'United States', 'location' => 'New York, United States', 'timezone' => 'America/New_York'],
        ['name' => 'Chicago', 'country' => 'United States', 'location' => 'Chicago, United States', 'timezone' => 'America/Chicago'],
        ['name' => 'Vancouver', 'country' => 'Canada', 'location' => 'Vancouver, Canada', 'timezone' => 'America/Vancouver'],
        ['name' => 'Kingston', 'country' => 'Jamaica', 'location' => 'Kingston, Jamaica', 'timezone' => 'America/Jamaica'],
        ['name' => 'Singapore', 'country' => 'Singapore', 'location' => 'Singapore', 'timezone' => 'Asia/Singapore'],
        ['name' => 'Manila', 'country' => 'Philippines', 'location' => 'Manila, Philippines', 'timezone' => 'Asia/Manila'],
        ['name' => 'Sydney', 'country' => 'Australia', 'location' => 'Sydney, Australia', 'timezone' => 'Australia/Sydney'],
        ['name' => 'Auckland', 'country' => 'New Zealand', 'location' => 'Auckland, New Zealand', 'timezone' => 'Pacific/Auckland', 'aliases' => ['Auckland New Zealand', 'New Zealand']],
    ],
];
